name: Simple Python CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Lint code (flake8)
        run: |
          pip install flake8
          flake8 main.py

      - name: Save main.py as artifact
        uses: actions/upload-artifact@v4
        with:
          name: script-artifact
          path: main.py

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download code artifact
        uses: actions/download-artifact@v4
        with:
          name: script-artifact

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Run test
        run: |
          echo 'def test_hello(): assert __import__("main").hello() == "Hello, GitHub Actions!"' > test_main.py
          pip install pytest
          pytest test_main.py

      - name: Save tested artifact
        uses: actions/upload-artifact@v4
        with:
          name: tested-script-artifact
          path: main.py

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Download tested artifact
        uses: actions/download-artifact@v4
        with:
          name: tested-script-artifact

      - name: "Fake deploy"
        run: |
          echo "Deploying script..."
          cat main.py
